// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCui9w2fCAzxfNW-x2GekOQMtS4yuttSTo',
    appId: '1:785043015012:web:c90da0c0d39815b4036671',
    messagingSenderId: '785043015012',
    projectId: 'project-30dd3c12-9d55-4261-bc5',
    authDomain: 'project-30dd3c12-9d55-4261-bc5.firebaseapp.com',
    storageBucket: 'project-30dd3c12-9d55-4261-bc5.firebasestorage.app',
    measurementId: 'G-JYKZBSWC3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHf8xRj92EHopbn4cIblOivCJkFrRmRgg',
    appId: '1:785043015012:android:387ef31f4df9afd9036671',
    messagingSenderId: '785043015012',
    projectId: 'project-30dd3c12-9d55-4261-bc5',
    storageBucket: 'project-30dd3c12-9d55-4261-bc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zrXN2jQaWXPrX_KxGuGqc828YlJK4_A',
    appId: '1:785043015012:ios:41f6990e24b2380a036671',
    messagingSenderId: '785043015012',
    projectId: 'project-30dd3c12-9d55-4261-bc5',
    storageBucket: 'project-30dd3c12-9d55-4261-bc5.firebasestorage.app',
    iosBundleId: 'com.example.clawcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-zrXN2jQaWXPrX_KxGuGqc828YlJK4_A',
    appId: '1:785043015012:ios:41f6990e24b2380a036671',
    messagingSenderId: '785043015012',
    projectId: 'project-30dd3c12-9d55-4261-bc5',
    storageBucket: 'project-30dd3c12-9d55-4261-bc5.firebasestorage.app',
    iosBundleId: 'com.example.clawcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCui9w2fCAzxfNW-x2GekOQMtS4yuttSTo',
    appId: '1:785043015012:web:dda9c0b057671d8b036671',
    messagingSenderId: '785043015012',
    projectId: 'project-30dd3c12-9d55-4261-bc5',
    authDomain: 'project-30dd3c12-9d55-4261-bc5.firebaseapp.com',
    storageBucket: 'project-30dd3c12-9d55-4261-bc5.firebasestorage.app',
    measurementId: 'G-ZXF1SGPZG9',
  );
}
